# *****************************************************************************
# Copyright (c) 2026, Intel Corporation
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# - Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# - Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# - Neither the name of the copyright holder nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.
# *****************************************************************************


from ._accumulation import cumulative_logsumexp, cumulative_prod, cumulative_sum
from ._array_api import __array_api_version__, __array_namespace_info__
from ._clip import clip
from ._compute_follows_data import (
    ExecutionPlacementError,
    get_coerced_usm_type,
    get_execution_queue,
    validate_usm_type,
)
from ._constants import e, inf, nan, newaxis, pi
from ._copy_utils import (
    asnumpy,
    astype,
    copy,
    from_numpy,
    to_numpy,
)
from ._ctors import (
    arange,
    asarray,
    empty,
    empty_like,
    eye,
    full,
    full_like,
    linspace,
    meshgrid,
    ones,
    ones_like,
    tril,
    triu,
    zeros,
    zeros_like,
)
from ._data_types import (
    bool,
    complex64,
    complex128,
    dtype,
    float16,
    float32,
    float64,
    int8,
    int16,
    int32,
    int64,
    uint8,
    uint16,
    uint32,
    uint64,
)
from ._device import Device
from ._dldevice_conversions import (
    dldevice_to_sycl_device,
    sycl_device_to_dldevice,
)
from ._dlpack import from_dlpack
from ._elementwise_funcs import (
    abs,
    acos,
    acosh,
    add,
    angle,
    asin,
    asinh,
    atan,
    atan2,
    atanh,
    bitwise_and,
    bitwise_invert,
    bitwise_left_shift,
    bitwise_or,
    bitwise_right_shift,
    bitwise_xor,
    cbrt,
    ceil,
    conj,
    copysign,
    cos,
    cosh,
    divide,
    equal,
    exp,
    exp2,
    expm1,
    floor,
    floor_divide,
    greater,
    greater_equal,
    hypot,
    imag,
    isfinite,
    isinf,
    isnan,
    less,
    less_equal,
    log,
    log1p,
    log2,
    log10,
    logaddexp,
    logical_and,
    logical_not,
    logical_or,
    logical_xor,
    maximum,
    minimum,
    multiply,
    negative,
    nextafter,
    not_equal,
    positive,
    pow,
    proj,
    real,
    reciprocal,
    remainder,
    round,
    rsqrt,
    sign,
    signbit,
    sin,
    sinh,
    sqrt,
    square,
    subtract,
    tan,
    tanh,
    trunc,
)
from ._indexing_functions import (
    extract,
    nonzero,
    place,
    put,
    put_along_axis,
    take,
    take_along_axis,
)
from ._linear_algebra_functions import (
    matmul,
    matrix_transpose,
    tensordot,
    vecdot,
)
from ._manipulation_functions import (
    broadcast_arrays,
    broadcast_to,
    concat,
    expand_dims,
    flip,
    moveaxis,
    permute_dims,
    repeat,
    roll,
    squeeze,
    stack,
    swapaxes,
    tile,
    unstack,
)
from ._print import (
    get_print_options,
    print_options,
    set_print_options,
    usm_ndarray_repr,
    usm_ndarray_str,
)
from ._reduction import (
    argmax,
    argmin,
    count_nonzero,
    logsumexp,
    max,
    min,
    prod,
    reduce_hypot,
    sum,
)

# isort: off
# placed here to avoid circular import
from ._usmarray import DLDeviceType, usm_ndarray

# isort: on
from ._reshape import reshape
from ._search_functions import where
from ._searchsorted import searchsorted
from ._set_functions import (
    isin,
    unique_all,
    unique_counts,
    unique_inverse,
    unique_values,
)
from ._sorting import argsort, sort, top_k
from ._statistical_functions import mean, std, var
from ._testing import allclose
from ._type_utils import can_cast, finfo, iinfo, isdtype, result_type
from ._utility_functions import all, any, diff

__all__ = [
    "Device",
    "DLDeviceType",
    "usm_ndarray",
    # data types
    "bool",
    "dtype",
    "int8",
    "uint8",
    "int16",
    "uint16",
    "int32",
    "uint32",
    "int64",
    "uint64",
    "float16",
    "float32",
    "float64",
    "complex64",
    "complex128",
    # constants
    "e",
    "inf",
    "nan",
    "newaxis",
    "pi",
    # functions
    "abs",
    "acos",
    "acosh",
    "add",
    "all",
    "allclose",
    "angle",
    "any",
    "arange",
    "argmax",
    "argmin",
    "argsort",
    "asarray",
    "asin",
    "asinh",
    "asnumpy",
    "astype",
    "atan",
    "atanh",
    "atan2",
    "bitwise_and",
    "bitwise_invert",
    "bitwise_left_shift",
    "bitwise_or",
    "bitwise_right_shift",
    "bitwise_xor",
    "broadcast_arrays",
    "broadcast_to",
    "can_cast",
    "cbrt",
    "ceil",
    "concat",
    "conj",
    "copy",
    "copysign",
    "cos",
    "cosh",
    "count_nonzero",
    "clip",
    "cumulative_logsumexp",
    "cumulative_prod",
    "cumulative_sum",
    "diff",
    "divide",
    "dldevice_to_sycl_device",
    "empty",
    "empty_like",
    "equal",
    "extract",
    "expand_dims",
    "eye",
    "exp",
    "exp2",
    "expm1",
    "finfo",
    "flip",
    "floor",
    "floor_divide",
    "from_dlpack",
    "from_numpy",
    "full",
    "full_like",
    "get_print_options",
    "greater",
    "greater_equal",
    "hypot",
    "iinfo",
    "imag",
    "isfinite",
    "isinf",
    "isdtype",
    "isin",
    "isnan",
    "less",
    "less_equal",
    "linspace",
    "log",
    "logaddexp",
    "logical_and",
    "logical_not",
    "logical_or",
    "logical_xor",
    "logsumexp",
    "log1p",
    "log2",
    "log10",
    "max",
    "maximum",
    "mean",
    "meshgrid",
    "min",
    "minimum",
    "moveaxis",
    "multiply",
    "permute_dims",
    "matmul",
    "matrix_transpose",
    "negative",
    "nextafter",
    "nonzero",
    "not_equal",
    "ones",
    "ones_like",
    "place",
    "positive",
    "pow",
    "print_options",
    "prod",
    "proj",
    "put",
    "put_along_axis",
    "real",
    "reciprocal",
    "reduce_hypot",
    "remainder",
    "repeat",
    "reshape",
    "result_type",
    "roll",
    "round",
    "rsqrt",
    "searchsorted",
    "set_print_options",
    "sign",
    "signbit",
    "sin",
    "sinh",
    "sort",
    "sqrt",
    "square",
    "squeeze",
    "stack",
    "std",
    "subtract",
    "sum",
    "swapaxes",
    "sycl_device_to_dldevice",
    "take",
    "take_along_axis",
    "tan",
    "tanh",
    "tensordot",
    "tile",
    "top_k",
    "to_numpy",
    "tril",
    "triu",
    "trunc",
    "unique_all",
    "unique_counts",
    "unique_inverse",
    "unique_values",
    "unstack",
    "usm_ndarray_repr",
    "usm_ndarray_str",
    "var",
    "vecdot",
    "where",
    "zeros",
    "zeros_like",
    "__array_api_version__",
    "__array_namespace_info__",
    # utilities
    "ExecutionPlacementError",
    "get_coerced_usm_type",
    "get_execution_queue",
    "validate_usm_type",
]
