var searchData=
[
  ['gemmbatchtypepairsupportfactory_0',['GemmBatchTypePairSupportFactory',['../structdpnp_1_1extensions_1_1blas_1_1types_1_1_gemm_batch_type_pair_support_factory.html',1,'dpnp::extensions::blas::types']]],
  ['gemmtypepairsupportfactory_1',['GemmTypePairSupportFactory',['../structdpnp_1_1extensions_1_1blas_1_1types_1_1_gemm_type_pair_support_factory.html',1,'dpnp::extensions::blas::types']]],
  ['gemvtypepairsupportfactory_2',['GemvTypePairSupportFactory',['../structdpnp_1_1extensions_1_1blas_1_1types_1_1_gemv_type_pair_support_factory.html',1,'dpnp::extensions::blas::types']]],
  ['geqrfbatchtypepairsupportfactory_3',['GeqrfBatchTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_geqrf_batch_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['geqrftypepairsupportfactory_4',['GeqrfTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_geqrf_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['gesvdtypepairsupportfactory_5',['GesvdTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_gesvd_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['gesvtypepairsupportfactory_6',['GesvTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_gesv_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['get_5fdpnp_5ffunction_5fptr_7',['get_dpnp_function_ptr',['../group___b_a_c_k_e_n_d___a_p_i.html#ga5d37203d4448c22f7b046710d639fd4e',1,'dpnp_iface_fptr.hpp']]],
  ['get_5fdpnp_5ffunction_5fptr1_8',['get_dpnp_function_ptr1',['../group___b_a_c_k_e_n_d___a_p_i.html#ga77f60af228fba6ec73c66217bd7a4ee7',1,'dpnp_iface_fptr.hpp']]],
  ['get_5fid_5fby_5fxyz_5finkernel_9',['get_id_by_xyz_inkernel',['../group___b_a_c_k_e_n_d___u_t_i_l_s.html#ga064c245ca5bae67e4c986442e22d484e',1,'dpnp_utils.hpp']]],
  ['get_5foutput_5fsize_10',['get_output_size',['../class_d_p_n_p_c__id.html#a79168b2adbe07a8099747374bba2c483',1,'DPNPC_id']]],
  ['get_5fshape_5foffsets_5finkernel_11',['get_shape_offsets_inkernel',['../group___b_a_c_k_e_n_d___u_t_i_l_s.html#ga4706968b8ce210d69309a0cae330cea5',1,'dpnp_utils.hpp']]],
  ['get_5fxyz_5fby_5fid_12',['get_xyz_by_id',['../group___b_a_c_k_e_n_d___u_t_i_l_s.html#ga81df4307ea53001fc552b6cd76c0ebf8',1,'dpnp_utils.hpp']]],
  ['get_5fxyz_5fid_5fby_5fid_5finkernel_13',['get_xyz_id_by_id_inkernel',['../group___b_a_c_k_e_n_d___u_t_i_l_s.html#gad37eb9ce0ad29590cc931a9b6cd538e2',1,'dpnp_utils.hpp']]],
  ['getrfbatchtypepairsupportfactory_14',['GetrfBatchTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getrf_batch_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['getrftypepairsupportfactory_15',['GetrfTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getrf_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['getribatchtypepairsupportfactory_16',['GetriBatchTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getri_batch_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['getrstypepairsupportfactory_17',['GetrsTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getrs_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]]
];
