//===----------- dpctl_ext_capi.h - Headers for dpctl_ext C-API  -*-C++-*-===//
//
//                   Data Parallel Extension for NumPy (dpnp)
//
// Copyright 2026 Intel Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//===----------------------------------------------------------------------===//
///
/// \file
/// This file provides access to dpctl_ext's C-API, primarily for accessing
/// usm_ndarray types generated by Cython.
///
/// The generated Cython headers are located in the build directory at:
///   ${CMAKE_BINARY_DIR}/dpctl_ext/tensor/
///
/// This header serves as the public API entry point and should be included
/// instead of directly including the generated headers.
//===----------------------------------------------------------------------===//

#pragma once

// Include the generated Cython C-API headers for usm_ndarray
// These headers are generated during build and placed in the build directory
#include <dpctl_ext/tensor/_usmarray.h>
#include <dpctl_ext/tensor/_usmarray_api.h>
