var searchData=
[
  ['gcdfunctor_0',['GcdFunctor',['../structdpnp_1_1kernels_1_1gcd_1_1_gcd_functor.html',1,'dpnp::kernels::gcd']]],
  ['gemmbatchtypepairsupportfactory_1',['GemmBatchTypePairSupportFactory',['../structdpnp_1_1extensions_1_1blas_1_1types_1_1_gemm_batch_type_pair_support_factory.html',1,'dpnp::extensions::blas::types']]],
  ['gemmtypepairsupportfactory_2',['GemmTypePairSupportFactory',['../structdpnp_1_1extensions_1_1blas_1_1types_1_1_gemm_type_pair_support_factory.html',1,'dpnp::extensions::blas::types']]],
  ['gemvtypepairsupportfactory_3',['GemvTypePairSupportFactory',['../structdpnp_1_1extensions_1_1blas_1_1types_1_1_gemv_type_pair_support_factory.html',1,'dpnp::extensions::blas::types']]],
  ['geqrfbatchtypepairsupportfactory_4',['GeqrfBatchTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_geqrf_batch_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['geqrftypepairsupportfactory_5',['GeqrfTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_geqrf_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['gesvdtypepairsupportfactory_6',['GesvdTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_gesvd_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['gesvtypepairsupportfactory_7',['GesvTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_gesv_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['get_5fdpnp_5ffunction_5fptr_8',['get_dpnp_function_ptr',['../group___b_a_c_k_e_n_d___a_p_i.html#ga5d37203d4448c22f7b046710d639fd4e',1,'dpnp_iface_fptr.hpp']]],
  ['get_5fdpnp_5ffunction_5fptr1_9',['get_dpnp_function_ptr1',['../group___b_a_c_k_e_n_d___a_p_i.html#ga77f60af228fba6ec73c66217bd7a4ee7',1,'dpnp_iface_fptr.hpp']]],
  ['get_5foutput_5fsize_10',['get_output_size',['../class_d_p_n_p_c__id.html#a79168b2adbe07a8099747374bba2c483',1,'DPNPC_id']]],
  ['get_5fshape_5foffsets_5finkernel_11',['get_shape_offsets_inkernel',['../group___b_a_c_k_e_n_d___u_t_i_l_s.html#ga4706968b8ce210d69309a0cae330cea5',1,'dpnp_utils.hpp']]],
  ['get_5fxyz_5fid_5fby_5fid_5finkernel_12',['get_xyz_id_by_id_inkernel',['../group___b_a_c_k_e_n_d___u_t_i_l_s.html#gad37eb9ce0ad29590cc931a9b6cd538e2',1,'dpnp_utils.hpp']]],
  ['getrfbatchtypepairsupportfactory_13',['GetrfBatchTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getrf_batch_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['getrftypepairsupportfactory_14',['GetrfTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getrf_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['getribatchtypepairsupportfactory_15',['GetriBatchTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getri_batch_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['getrstypepairsupportfactory_16',['GetrsTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getrs_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]]
];
