var hierarchy =
[
    [ "dpnp::backend::ext::vm::AddContigFactory< fnT, T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_add_contig_factory.html", null ],
    [ "dpnp::backend::ext::vm::types::AddOutputType< T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_add_output_type.html", null ],
    [ "backend_sycl", "classbackend__sycl.html", null ],
    [ "dpnp::backend::ext::sycl_ext::cartesian_product< Args >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1cartesian__product.html", null ],
    [ "dpnp::backend::ext::sycl_ext::cartesian_product< std::tuple< std::tuple< FirstTupleArgs... > > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1cartesian__product_3_01std_1_1tuple_3_01std_1_1tupl8eeb66d10f7723d0fc0b38e3d181763c.html", null ],
    [ "dpnp::backend::ext::sycl_ext::cartesian_product< std::tuple< Tuples... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1cartesian__product_3_01std_1_1tuple_3_01_tuples_8_8_8_01_4_01_4.html", null ],
    [ "dpnp::backend::ext::sycl_ext::cartesian_product_impl< Args >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1cartesian__product__impl.html", null ],
    [ "dpnp::backend::ext::sycl_ext::cartesian_product_impl< std::tuple< std::tuple< T > >, std::tuple< SecondTupleArgs... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1cartesian__product__impl_3_01std_1_1tuple_3_01std_17b2e4d9f422d6a255a67e036ce4e46b3.html", null ],
    [ "dpnp::backend::ext::sycl_ext::cartesian_product_impl< std::tuple< std::tuple< T >, FirstTupleArgs... >, std::tuple< SecondTupleArgs... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1cartesian__product__impl_3_01std_1_1tuple_3_01std_1eacc8a58f076baec98f1eb11bc1030e3.html", null ],
    [ "dpnp::backend::ext::sycl_ext::CartesianDispatcher< C, FnT, DispatchT, Matcher, Axis >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1_cartesian_dispatcher.html", null ],
    [ "dpnp::backend::ext::vm::CeilContigFactory< fnT, T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_ceil_contig_factory.html", null ],
    [ "dpnp::backend::ext::vm::types::CeilOutputType< T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_ceil_output_type.html", null ],
    [ "dpnp::backend::ext::vm::ConjContigFactory< fnT, T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_conj_contig_factory.html", null ],
    [ "dpnp::backend::ext::vm::types::ConjOutputType< T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_conj_output_type.html", null ],
    [ "std::conjunction", null, [
      [ "are_same< T, Ts >", "structare__same.html", null ]
    ] ],
    [ "dpnp::backend::ext::sycl_ext::coord_in_space< DispatchT, Matcher, AxisData >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1coord__in__space.html", null ],
    [ "dpnp::backend::ext::sycl_ext::coord_in_space< DispatchT, Matcher, std::tuple< Axises... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1coord__in__space_3_01_dispatch_t_00_01_matcher_00_02eb2bcf087b8888b023b145a4e539e4d.html", null ],
    [ "dpnp::backend::ext::sycl_ext::coord_in_space< DispatchT, Matcher, std::tuple< CurrentAxis > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1coord__in__space_3_01_dispatch_t_00_01_matcher_00_09145d8edb59d4cea6805114cb85ebe7b.html", null ],
    [ "dpnp::backend::ext::vm::CosContigFactory< fnT, T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_cos_contig_factory.html", null ],
    [ "dpnp::backend::ext::vm::types::CosOutputType< T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_cos_output_type.html", null ],
    [ "std::disjunction", null, [
      [ "is_any< T, Ts >", "structis__any.html", null ]
    ] ],
    [ "dpnp::backend::ext::vm::DivContigFactory< fnT, T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_div_contig_factory.html", null ],
    [ "dpnp::backend::ext::vm::types::DivOutputType< T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_div_output_type.html", null ],
    [ "dpnp_less_comp", "classdpnp__less__comp.html", null ],
    [ "DPNP_USM_iterator< _Tp >", "class_d_p_n_p___u_s_m__iterator.html", null ],
    [ "DPNPC_id< _Tp >", "class_d_p_n_p_c__id.html", null ],
    [ "DPNPC_ptr_adapter< _DataType >", "class_d_p_n_p_c__ptr__adapter.html", null ],
    [ "DPNPFuncData", "struct_d_p_n_p_func_data.html", null ],
    [ "dpnp::backend::ext::sycl_ext::elements_count< Tuple >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1elements__count.html", null ],
    [ "dpnp::backend::ext::sycl_ext::elements_count< std::tuple< T > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1elements__count_3_01std_1_1tuple_3_01_t_01_4_01_4.html", null ],
    [ "dpnp::backend::ext::sycl_ext::elements_count< std::tuple< T, Axis... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1elements__count_3_01std_1_1tuple_3_01_t_00_01_axis_8_8_8_01_4_01_4.html", null ],
    [ "engine_struct", "structengine__struct.html", [
      [ "mcg59_struct", "structmcg59__struct.html", null ],
      [ "mt19937_struct", "structmt19937__struct.html", null ]
    ] ],
    [ "dpnp::backend::ext::sycl_ext::extend_tuple_type< Tuple, T >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1extend__tuple__type.html", null ],
    [ "dpnp::backend::ext::sycl_ext::extend_tuple_type< std::tuple< Args... >, T >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1extend__tuple__type_3_01std_1_1tuple_3_01_args_8_8_8_01_4_00_01_t_01_4.html", null ],
    [ "dpnp::backend::ext::vm::FloorContigFactory< fnT, T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_floor_contig_factory.html", null ],
    [ "dpnp::backend::ext::vm::types::FloorOutputType< T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_floor_output_type.html", null ],
    [ "func_type_pair_t< FuncType, T >", "structfunc__type__pair__t.html", null ],
    [ "dpnp::backend::ext::sycl_ext::get_linear_id< Tuple >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1get__linear__id.html", null ],
    [ "dpnp::backend::ext::sycl_ext::get_linear_id< std::tuple< T > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1get__linear__id_3_01std_1_1tuple_3_01_t_01_4_01_4.html", null ],
    [ "dpnp::backend::ext::sycl_ext::get_linear_id< std::tuple< T, Axis... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1get__linear__id_3_01std_1_1tuple_3_01_t_00_01_axis_8_8_8_01_4_01_4.html", null ],
    [ "dpnp::backend::ext::lapack::types::HeevdTypePairSupportFactory< T, RealT >", "structdpnp_1_1backend_1_1ext_1_1lapack_1_1types_1_1_heevd_type_pair_support_factory.html", null ],
    [ "dpnp::backend::ext::sycl_ext::index_on_axis< idx, DispatchT, Matcher, Tuple >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1index__on__axis.html", null ],
    [ "dpnp::backend::ext::sycl_ext::index_on_axis< idx, DispatchT, Matcher, std::tuple< AxisData... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1index__on__axis_3_01idx_00_01_dispatch_t_00_01_matc014615cac12293ef2d15243fdee2c449.html", null ],
    [ "dpnp::backend::ext::sycl_ext::index_on_axis< idx, DispatchT, Matcher, std::tuple< T > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1index__on__axis_3_01idx_00_01_dispatch_t_00_01_matcafd2cf8593c2aa4d8a9103f019cc37b1.html", null ],
    [ "dpnp::backend::ext::vm::LnContigFactory< fnT, T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_ln_contig_factory.html", null ],
    [ "dpnp::backend::ext::vm::types::LnOutputType< T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_ln_output_type.html", null ],
    [ "dpnp::backend::ext::sycl_ext::merge_two_inner_tuple_types< FirstTuple, SecondTuple >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1merge__two__inner__tuple__types.html", null ],
    [ "dpnp::backend::ext::sycl_ext::merge_two_inner_tuple_types< std::tuple< FirstTupleArgs... >, std::tuple< SecondTupleArgs... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1merge__two__inner__tuple__types_3_01std_1_1tuple_3_0138ac4b60360159f3bcb33d2fa44168.html", null ],
    [ "dpnp::backend::ext::sycl_ext::merge_two_inner_tuple_types< std::tuple< std::tuple< FirstTupleArgs... > >, std::tuple< std::tuple< SecondTupleArgs... > > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1merge__two__inner__tuple__types_3_01std_1_1tuple_3_61a32514aa73a4b8a3b7c6a5b4f77028.html", null ],
    [ "dpnp::backend::ext::sycl_ext::merge_two_tuple_types< FirstTuple, SecondTuple >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1merge__two__tuple__types.html", null ],
    [ "dpnp::backend::ext::sycl_ext::merge_two_tuple_types< std::tuple< FirstTupleArgs... >, std::tuple< SecondTupleArgs... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1merge__two__tuple__types_3_01std_1_1tuple_3_01_firsbb11e9f600ace9f62066d6e14ad141b6.html", null ],
    [ "dpnp::backend::ext::vm::MulContigFactory< fnT, T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_mul_contig_factory.html", null ],
    [ "dpnp::backend::ext::vm::types::MulOutputType< T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_mul_output_type.html", null ],
    [ "dpnp::backend::ext::sycl_ext::pop_tuple_type< Tuple >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1pop__tuple__type.html", null ],
    [ "dpnp::backend::ext::sycl_ext::pop_tuple_type< std::tuple< T, Args... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1pop__tuple__type_3_01std_1_1tuple_3_01_t_00_01_args_8_8_8_01_4_01_4.html", null ],
    [ "dpnp::backend::ext::sycl_ext::populate_table< C, FnT, Tuple >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1populate__table.html", null ],
    [ "dpnp::backend::ext::sycl_ext::populate_table< C, FnT, std::tuple< Args... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1populate__table_3_01_c_00_01_fn_t_00_01std_1_1tuple_3_01_args_8_8_8_01_4_01_4.html", null ],
    [ "dpnp::backend::ext::sycl_ext::populate_table< C, FnT, std::tuple< std::tuple< Args... > > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1populate__table_3_01_c_00_01_fn_t_00_01std_1_1tuple0f7ffe7646d3c8f7f12eca20777caefd.html", null ],
    [ "dpnp::backend::ext::vm::PowContigFactory< fnT, T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_pow_contig_factory.html", null ],
    [ "dpnp::backend::ext::vm::types::PowOutputType< T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_pow_output_type.html", null ],
    [ "python_constants", "structpython__constants.html", null ],
    [ "dpnp::backend::ext::sycl_ext::resolve_type< C, Tuple >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1resolve__type.html", null ],
    [ "dpnp::backend::ext::sycl_ext::resolve_type< C, std::tuple< Args... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1resolve__type_3_01_c_00_01std_1_1tuple_3_01_args_8_8_8_01_4_01_4.html", null ],
    [ "dpnp::backend::ext::vm::RoundContigFactory< fnT, T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_round_contig_factory.html", null ],
    [ "dpnp::backend::ext::vm::types::RoundOutputType< T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_round_output_type.html", null ],
    [ "dpnp::backend::ext::vm::SinContigFactory< fnT, T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_sin_contig_factory.html", null ],
    [ "dpnp::backend::ext::vm::types::SinOutputType< T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_sin_output_type.html", null ],
    [ "dpnp::backend::ext::vm::SqrContigFactory< fnT, T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_sqr_contig_factory.html", null ],
    [ "dpnp::backend::ext::vm::types::SqrOutputType< T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_sqr_output_type.html", null ],
    [ "dpnp::backend::ext::vm::SqrtContigFactory< fnT, T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_sqrt_contig_factory.html", null ],
    [ "dpnp::backend::ext::vm::types::SqrtOutputType< T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_sqrt_output_type.html", null ],
    [ "dpnp::backend::ext::vm::SubContigFactory< fnT, T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_sub_contig_factory.html", null ],
    [ "dpnp::backend::ext::vm::types::SubOutputType< T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_sub_output_type.html", null ],
    [ "dpnp::backend::ext::sycl_ext::sum_mean< InT, OutT, Mean >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1sum__mean.html", null ],
    [ "dpnp::backend::ext::lapack::types::SyevdTypePairSupportFactory< T >", "structdpnp_1_1backend_1_1ext_1_1lapack_1_1types_1_1_syevd_type_pair_support_factory.html", null ],
    [ "dpnp::backend::ext::vm::TruncContigFactory< fnT, T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_trunc_contig_factory.html", null ],
    [ "dpnp::backend::ext::vm::types::TruncOutputType< T >", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_trunc_output_type.html", null ],
    [ "dpnp::backend::ext::sycl_ext::tuple_of_n_elements< T, N >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1tuple__of__n__elements.html", null ],
    [ "dpnp::backend::ext::sycl_ext::tuple_of_n_elements< T, 0 >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1tuple__of__n__elements_3_01_t_00_010_01_4.html", null ],
    [ "dpnp::backend::ext::sycl_ext::tuple_of_n_elements< T, 1 >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1tuple__of__n__elements_3_01_t_00_011_01_4.html", null ],
    [ "dpnp::backend::ext::sycl_ext::tuple_of_tuples< Args >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1tuple__of__tuples.html", null ],
    [ "dpnp::backend::ext::sycl_ext::tuple_of_tuples< std::tuple< Args... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1tuple__of__tuples_3_01std_1_1tuple_3_01_args_8_8_8_01_4_01_4.html", null ],
    [ "dpnp::backend::ext::sycl_ext::tuple_of_tuples< std::tuple< T > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1tuple__of__tuples_3_01std_1_1tuple_3_01_t_01_4_01_4.html", null ],
    [ "dpnp::backend::ext::sycl_ext::UsmArrayMatcher", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1_usm_array_matcher.html", null ],
    [ "Ps", null, [
      [ "func_type_map_factory_t< Ps >", "structfunc__type__map__factory__t.html", null ]
    ] ]
];