#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

from datetime import datetime
from urllib.parse import urljoin

from jinja2.sandbox import SandboxedEnvironment
from numpydoc.docscrape import NumpyDocString
from numpydoc.docscrape_sphinx import SphinxDocString
from sphinx.ext.autodoc import FunctionDocumenter

from dpnp.dpnp_algo.dpnp_elementwise_common import (
    DPNPBinaryFunc,
    DPNPBinaryFuncOutKw,
    DPNPBinaryTwoOutputsFunc,
    DPNPUnaryFunc,
    DPNPUnaryTwoOutputsFunc,
)

try:
    import comparison_generator
except ImportError:
    # If extensions (or modules to document with autodoc) are in another directory,
    # add these directories to sys.path here. If the directory is relative to the
    # documentation root, use os.path.abspath to make it absolute, like shown here.
    import os
    import sys

    sys.path.insert(0, os.path.abspath("."))
    import comparison_generator


# Generate comparison table.
with open("reference/comparison_table.rst.inc", "w") as fd:
    fd.write(comparison_generator.generate())

import dpnp

# -- Project information -----------------------------------------------------

project = "Data Parallel Extension for NumPy"
year = datetime.now().year
copyright = f"2020-{year}, Intel Corporation"
author = "Intel"

# Strip local version identifiers (e.g. git hash) from the version string
version = release = dpnp.__version__.split("+")[0]


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinx.ext.intersphinx",
    "numpydoc",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinxcontrib.googleanalytics",
    "sphinxcontrib.spelling",
]

copybutton_prompt_text = r">>> |\.\.\. "
copybutton_prompt_is_regexp = True

googleanalytics_id = "G-554F8VNE28"
googleanalytics_enabled = True

# Enable a misspelling as a sphinx warning
spelling_warning = True

# Define a list of words known to be spelled correctly
spelling_word_list_filename = "known_words.txt"

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "default"


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "furo"
# TODO: Remove html_title and uncomment html_logo once dpnp.svg is available
html_title = f"Data Parallel Extension for NumPy (dpnp) {release} documentation"
html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# html_logo = "_static/dpnp.svg"
# html_favicon = "_static/dpnp.svg"
html_css_files = ["dpnp-custom.css"]
html_js_files = ["dpnp-custom.js"]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "dpnpdoc"


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "dpnp.tex", "dpnp Documentation", "Intel", "manual"),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "dpnp", "dpnp Documentation", [author], 1)]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "dpnp",
        "dpnp Documentation",
        author,
        "dpnp",
        "One line description of project.",
        "Miscellaneous",
    ),
]


# -- Extension configuration -------------------------------------------------


# -- Options for todo extension ----------------------------------------------
def _can_document_member(member, *args, **kwargs):
    if isinstance(
        member,
        (
            DPNPBinaryFunc,
            DPNPBinaryFuncOutKw,
            DPNPBinaryTwoOutputsFunc,
            DPNPUnaryFunc,
            DPNPUnaryTwoOutputsFunc,
        ),
    ):
        return True
    return orig(member, *args, **kwargs)


documenter = FunctionDocumenter
orig = documenter.can_document_member
documenter.can_document_member = _can_document_member

autosummary_generate = True

_DPCTL_021_BASE = "https://intelpython.github.io/dpctl/0.21.1/"
_DPCTL_021_INV = urljoin(_DPCTL_021_BASE, "objects.inv")

intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/reference/", None),
    "dpctl": ("https://intelpython.github.io/dpctl/latest/", None),
    "cupy": ("https://docs.cupy.dev/en/stable/", None),
}

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# Members come from autosummary; don't let numpydoc duplicate them
numpydoc_show_class_members = False

# Keep the dpnp-only "Limitations" section (numpydoc drops unknown sections):
# register it and give it a slot in the template below
NumpyDocString.sections.setdefault("Limitations", [])

_NUMPYDOC_TEMPLATE = """\
{{index}}
{{summary}}
{{extended_summary}}
{{parameters}}
{{attributes}}
{{methods}}
{{returns}}
{{yields}}
{{receives}}
{{other_parameters}}
{{raises}}
{{warns}}
{{warnings}}
{{limitations}}
{{see_also}}
{{notes}}
{{references}}
{{examples}}
"""

_orig_load_config = SphinxDocString.load_config


def _load_config_with_limitations(self, config):
    _orig_load_config(self, config)
    # Use our template with the "limitations" slot
    self.template = SandboxedEnvironment().from_string(_NUMPYDOC_TEMPLATE)


SphinxDocString.load_config = _load_config_with_limitations

_orig_str = SphinxDocString.__str__


def _str_with_limitations(self, indent=0, func_role="obj"):
    # Wrap render() to fill the "limitations" slot (a rubric, like "Notes")
    orig_render = self.template.render

    def render(**ns):
        ns["limitations"] = "\n".join(self._str_section("Limitations"))
        return orig_render(**ns)

    self.template.render = render
    try:
        return _orig_str(self, indent=indent, func_role=func_role)
    finally:
        self.template.render = orig_render


SphinxDocString.__str__ = _str_with_limitations


# TODO: Remove once dpnp.tensor docs are generated in dpnp
def _load_dpctl_tensor_inventory(app):
    """Load dpctl 0.21.1 inventory for dpnp.tensor fallback only."""
    from sphinx.ext.intersphinx import fetch_inventory
    from sphinx.util import logging

    logger = logging.getLogger(__name__)

    try:
        inv = fetch_inventory(app, _DPCTL_021_BASE, _DPCTL_021_INV)
    except Exception as exc:
        logger.warning(
            "Failed to load dpctl 0.21.1 inventory from %s: %s",
            _DPCTL_021_INV,
            exc,
        )
        inv = {}

    app.builder.env._dpctl_tensor_021_inventory = inv


# TODO: Remove once dpnp.tensor docs are generated in dpnp
def _resolve_dpnp_tensor_refs(app, env, node, contnode):
    """Resolve dpnp.tensor.* references to dpctl 0.21.1 documentation.

    This temporary workaround is needed because dpnp.tensor documentation
    is not generated yet, while the corresponding API is still documented
    in dpctl 0.21.1.
    """
    from docutils import nodes as docutils_nodes

    target = node.get("reftarget", "")
    if not target.startswith("dpnp.tensor"):
        return None

    dpctl_target = target.replace("dpnp.tensor", "dpctl.tensor", 1)
    dpctl_tensor_inv = getattr(env, "_dpctl_tensor_021_inventory", {})

    for _objtype, objects in dpctl_tensor_inv.items():
        if dpctl_target not in objects:
            continue

        item = objects[dpctl_target]
        location = item.uri
        if location.endswith("$"):
            location = location[:-1] + dpctl_target

        refuri = urljoin(_DPCTL_021_BASE, location)
        newnode = docutils_nodes.reference(
            "", "", internal=False, refuri=refuri
        )
        newnode += contnode.deepcopy()
        return newnode

    return None


def setup(app):
    app.connect("builder-inited", _load_dpctl_tensor_inventory, priority=400)
    app.connect("missing-reference", _resolve_dpnp_tensor_refs, priority=400)
