var annotated_dup =
[
    [ "dpnp", null, [
      [ "backend", null, [
        [ "ext", null, [
          [ "lapack", null, [
            [ "types", null, [
              [ "HeevdTypePairSupportFactory", "structdpnp_1_1backend_1_1ext_1_1lapack_1_1types_1_1_heevd_type_pair_support_factory.html", null ],
              [ "SyevdTypePairSupportFactory", "structdpnp_1_1backend_1_1ext_1_1lapack_1_1types_1_1_syevd_type_pair_support_factory.html", null ]
            ] ]
          ] ],
          [ "sycl_ext", null, [
            [ "cartesian_product", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1cartesian__product.html", null ],
            [ "cartesian_product< std::tuple< std::tuple< FirstTupleArgs... > > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1cartesian__product_3_01std_1_1tuple_3_01std_1_1tupl8eeb66d10f7723d0fc0b38e3d181763c.html", null ],
            [ "cartesian_product< std::tuple< Tuples... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1cartesian__product_3_01std_1_1tuple_3_01_tuples_8_8_8_01_4_01_4.html", null ],
            [ "cartesian_product_impl", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1cartesian__product__impl.html", null ],
            [ "cartesian_product_impl< std::tuple< std::tuple< T > >, std::tuple< SecondTupleArgs... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1cartesian__product__impl_3_01std_1_1tuple_3_01std_17b2e4d9f422d6a255a67e036ce4e46b3.html", null ],
            [ "cartesian_product_impl< std::tuple< std::tuple< T >, FirstTupleArgs... >, std::tuple< SecondTupleArgs... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1cartesian__product__impl_3_01std_1_1tuple_3_01std_1eacc8a58f076baec98f1eb11bc1030e3.html", null ],
            [ "CartesianDispatcher", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1_cartesian_dispatcher.html", null ],
            [ "coord_in_space", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1coord__in__space.html", null ],
            [ "coord_in_space< DispatchT, Matcher, std::tuple< Axises... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1coord__in__space_3_01_dispatch_t_00_01_matcher_00_02eb2bcf087b8888b023b145a4e539e4d.html", null ],
            [ "coord_in_space< DispatchT, Matcher, std::tuple< CurrentAxis > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1coord__in__space_3_01_dispatch_t_00_01_matcher_00_09145d8edb59d4cea6805114cb85ebe7b.html", null ],
            [ "elements_count", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1elements__count.html", null ],
            [ "elements_count< std::tuple< T > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1elements__count_3_01std_1_1tuple_3_01_t_01_4_01_4.html", null ],
            [ "elements_count< std::tuple< T, Axis... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1elements__count_3_01std_1_1tuple_3_01_t_00_01_axis_8_8_8_01_4_01_4.html", null ],
            [ "extend_tuple_type", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1extend__tuple__type.html", null ],
            [ "extend_tuple_type< std::tuple< Args... >, T >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1extend__tuple__type_3_01std_1_1tuple_3_01_args_8_8_8_01_4_00_01_t_01_4.html", null ],
            [ "get_linear_id", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1get__linear__id.html", null ],
            [ "get_linear_id< std::tuple< T > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1get__linear__id_3_01std_1_1tuple_3_01_t_01_4_01_4.html", null ],
            [ "get_linear_id< std::tuple< T, Axis... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1get__linear__id_3_01std_1_1tuple_3_01_t_00_01_axis_8_8_8_01_4_01_4.html", null ],
            [ "index_on_axis", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1index__on__axis.html", null ],
            [ "index_on_axis< idx, DispatchT, Matcher, std::tuple< AxisData... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1index__on__axis_3_01idx_00_01_dispatch_t_00_01_matc014615cac12293ef2d15243fdee2c449.html", null ],
            [ "index_on_axis< idx, DispatchT, Matcher, std::tuple< T > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1index__on__axis_3_01idx_00_01_dispatch_t_00_01_matcafd2cf8593c2aa4d8a9103f019cc37b1.html", null ],
            [ "merge_two_inner_tuple_types", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1merge__two__inner__tuple__types.html", null ],
            [ "merge_two_inner_tuple_types< std::tuple< FirstTupleArgs... >, std::tuple< SecondTupleArgs... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1merge__two__inner__tuple__types_3_01std_1_1tuple_3_0138ac4b60360159f3bcb33d2fa44168.html", null ],
            [ "merge_two_inner_tuple_types< std::tuple< std::tuple< FirstTupleArgs... > >, std::tuple< std::tuple< SecondTupleArgs... > > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1merge__two__inner__tuple__types_3_01std_1_1tuple_3_61a32514aa73a4b8a3b7c6a5b4f77028.html", null ],
            [ "merge_two_tuple_types", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1merge__two__tuple__types.html", null ],
            [ "merge_two_tuple_types< std::tuple< FirstTupleArgs... >, std::tuple< SecondTupleArgs... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1merge__two__tuple__types_3_01std_1_1tuple_3_01_firsbb11e9f600ace9f62066d6e14ad141b6.html", null ],
            [ "pop_tuple_type", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1pop__tuple__type.html", null ],
            [ "pop_tuple_type< std::tuple< T, Args... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1pop__tuple__type_3_01std_1_1tuple_3_01_t_00_01_args_8_8_8_01_4_01_4.html", null ],
            [ "populate_table", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1populate__table.html", null ],
            [ "populate_table< C, FnT, std::tuple< Args... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1populate__table_3_01_c_00_01_fn_t_00_01std_1_1tuple_3_01_args_8_8_8_01_4_01_4.html", null ],
            [ "populate_table< C, FnT, std::tuple< std::tuple< Args... > > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1populate__table_3_01_c_00_01_fn_t_00_01std_1_1tuple0f7ffe7646d3c8f7f12eca20777caefd.html", null ],
            [ "resolve_type", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1resolve__type.html", null ],
            [ "resolve_type< C, std::tuple< Args... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1resolve__type_3_01_c_00_01std_1_1tuple_3_01_args_8_8_8_01_4_01_4.html", null ],
            [ "sum_mean", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1sum__mean.html", null ],
            [ "tuple_of_n_elements", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1tuple__of__n__elements.html", null ],
            [ "tuple_of_n_elements< T, 0 >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1tuple__of__n__elements_3_01_t_00_010_01_4.html", null ],
            [ "tuple_of_n_elements< T, 1 >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1tuple__of__n__elements_3_01_t_00_011_01_4.html", null ],
            [ "tuple_of_tuples", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1tuple__of__tuples.html", null ],
            [ "tuple_of_tuples< std::tuple< Args... > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1tuple__of__tuples_3_01std_1_1tuple_3_01_args_8_8_8_01_4_01_4.html", null ],
            [ "tuple_of_tuples< std::tuple< T > >", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1tuple__of__tuples_3_01std_1_1tuple_3_01_t_01_4_01_4.html", null ],
            [ "UsmArrayMatcher", "structdpnp_1_1backend_1_1ext_1_1sycl__ext_1_1_usm_array_matcher.html", null ]
          ] ],
          [ "vm", null, [
            [ "types", null, [
              [ "AbsOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_abs_output_type.html", null ],
              [ "AcoshOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_acosh_output_type.html", null ],
              [ "AcosOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_acos_output_type.html", null ],
              [ "AddOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_add_output_type.html", null ],
              [ "AsinhOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_asinh_output_type.html", null ],
              [ "AsinOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_asin_output_type.html", null ],
              [ "Atan2OutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_atan2_output_type.html", null ],
              [ "AtanhOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_atanh_output_type.html", null ],
              [ "AtanOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_atan_output_type.html", null ],
              [ "CbrtOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_cbrt_output_type.html", null ],
              [ "CeilOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_ceil_output_type.html", null ],
              [ "ConjOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_conj_output_type.html", null ],
              [ "CoshOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_cosh_output_type.html", null ],
              [ "CosOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_cos_output_type.html", null ],
              [ "DivOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_div_output_type.html", null ],
              [ "Exp2OutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_exp2_output_type.html", null ],
              [ "Expm1OutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_expm1_output_type.html", null ],
              [ "ExpOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_exp_output_type.html", null ],
              [ "FloorOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_floor_output_type.html", null ],
              [ "HypotOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_hypot_output_type.html", null ],
              [ "LnOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_ln_output_type.html", null ],
              [ "Log10OutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_log10_output_type.html", null ],
              [ "Log1pOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_log1p_output_type.html", null ],
              [ "Log2OutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_log2_output_type.html", null ],
              [ "MulOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_mul_output_type.html", null ],
              [ "PowOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_pow_output_type.html", null ],
              [ "RoundOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_round_output_type.html", null ],
              [ "SinhOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_sinh_output_type.html", null ],
              [ "SinOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_sin_output_type.html", null ],
              [ "SqrOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_sqr_output_type.html", null ],
              [ "SqrtOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_sqrt_output_type.html", null ],
              [ "SubOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_sub_output_type.html", null ],
              [ "TanhOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_tanh_output_type.html", null ],
              [ "TanOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_tan_output_type.html", null ],
              [ "TruncOutputType", "structdpnp_1_1backend_1_1ext_1_1vm_1_1types_1_1_trunc_output_type.html", null ]
            ] ],
            [ "AbsContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_abs_contig_factory.html", null ],
            [ "AcosContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_acos_contig_factory.html", null ],
            [ "AcoshContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_acosh_contig_factory.html", null ],
            [ "AddContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_add_contig_factory.html", null ],
            [ "AsinContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_asin_contig_factory.html", null ],
            [ "AsinhContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_asinh_contig_factory.html", null ],
            [ "Atan2ContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_atan2_contig_factory.html", null ],
            [ "AtanContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_atan_contig_factory.html", null ],
            [ "AtanhContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_atanh_contig_factory.html", null ],
            [ "CbrtContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_cbrt_contig_factory.html", null ],
            [ "CeilContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_ceil_contig_factory.html", null ],
            [ "ConjContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_conj_contig_factory.html", null ],
            [ "CosContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_cos_contig_factory.html", null ],
            [ "CoshContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_cosh_contig_factory.html", null ],
            [ "DivContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_div_contig_factory.html", null ],
            [ "Exp2ContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_exp2_contig_factory.html", null ],
            [ "ExpContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_exp_contig_factory.html", null ],
            [ "Expm1ContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_expm1_contig_factory.html", null ],
            [ "FloorContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_floor_contig_factory.html", null ],
            [ "HypotContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_hypot_contig_factory.html", null ],
            [ "LnContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_ln_contig_factory.html", null ],
            [ "Log10ContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_log10_contig_factory.html", null ],
            [ "Log1pContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_log1p_contig_factory.html", null ],
            [ "Log2ContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_log2_contig_factory.html", null ],
            [ "MulContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_mul_contig_factory.html", null ],
            [ "PowContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_pow_contig_factory.html", null ],
            [ "RoundContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_round_contig_factory.html", null ],
            [ "SinContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_sin_contig_factory.html", null ],
            [ "SinhContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_sinh_contig_factory.html", null ],
            [ "SqrContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_sqr_contig_factory.html", null ],
            [ "SqrtContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_sqrt_contig_factory.html", null ],
            [ "SubContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_sub_contig_factory.html", null ],
            [ "TanContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_tan_contig_factory.html", null ],
            [ "TanhContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_tanh_contig_factory.html", null ],
            [ "TruncContigFactory", "structdpnp_1_1backend_1_1ext_1_1vm_1_1_trunc_contig_factory.html", null ]
          ] ]
        ] ]
      ] ]
    ] ],
    [ "are_same", "structare__same.html", null ],
    [ "backend_sycl", "classbackend__sycl.html", "classbackend__sycl" ],
    [ "dpnp_less_comp", "classdpnp__less__comp.html", null ],
    [ "DPNP_USM_iterator", "class_d_p_n_p___u_s_m__iterator.html", "class_d_p_n_p___u_s_m__iterator" ],
    [ "DPNPC_id", "class_d_p_n_p_c__id.html", "class_d_p_n_p_c__id" ],
    [ "DPNPC_ptr_adapter", "class_d_p_n_p_c__ptr__adapter.html", null ],
    [ "DPNPFuncData", "struct_d_p_n_p_func_data.html", "struct_d_p_n_p_func_data" ],
    [ "engine_struct", "structengine__struct.html", null ],
    [ "func_type_map_factory_t", "structfunc__type__map__factory__t.html", null ],
    [ "func_type_pair_t", "structfunc__type__pair__t.html", null ],
    [ "is_any", "structis__any.html", null ],
    [ "is_complex", "structis__complex.html", null ],
    [ "mcg59_struct", "structmcg59__struct.html", null ],
    [ "mt19937_struct", "structmt19937__struct.html", null ],
    [ "python_constants", "structpython__constants.html", null ]
];