var annotated_dup =
[
    [ "_argsort_less", "struct__argsort__less.html", "struct__argsort__less" ],
    [ "_sort_less", "struct__sort__less.html", "struct__sort__less" ],
    [ "backend_sycl", "classbackend__sycl.html", "classbackend__sycl" ],
    [ "custom_argmax_c_kernel", "classcustom__argmax__c__kernel.html", null ],
    [ "custom_argmin_c_kernel", "classcustom__argmin__c__kernel.html", null ],
    [ "custom_argsort_c_kernel", "classcustom__argsort__c__kernel.html", null ],
    [ "custom_cholesky_c_kernel", "classcustom__cholesky__c__kernel.html", null ],
    [ "custom_cov_c_kernel", "classcustom__cov__c__kernel.html", null ],
    [ "custom_det_c_kernel", "classcustom__det__c__kernel.html", null ],
    [ "custom_elemwise_absolute_c_kernel", "classcustom__elemwise__absolute__c__kernel.html", null ],
    [ "custom_elemwise_transpose_c_kernel", "classcustom__elemwise__transpose__c__kernel.html", null ],
    [ "custom_matrix_rank_c_kernel", "classcustom__matrix__rank__c__kernel.html", null ],
    [ "custom_max_c_kernel", "classcustom__max__c__kernel.html", null ],
    [ "custom_min_c_kernel", "classcustom__min__c__kernel.html", null ],
    [ "custom_prod_c_kernel", "classcustom__prod__c__kernel.html", null ],
    [ "custom_sort_c_kernel", "classcustom__sort__c__kernel.html", null ],
    [ "custom_sum_c_kernel", "classcustom__sum__c__kernel.html", null ],
    [ "custom_var_c_kernel", "classcustom__var__c__kernel.html", null ],
    [ "dpnp_arange_c_kernel", "classdpnp__arange__c__kernel.html", null ],
    [ "dpnp_correlate_c_kernel", "classdpnp__correlate__c__kernel.html", null ],
    [ "dpnp_dot_c_kernel", "classdpnp__dot__c__kernel.html", null ],
    [ "dpnp_fft_fft_c_kernel", "classdpnp__fft__fft__c__kernel.html", null ],
    [ "dpnp_floor_divide_c_kernel", "classdpnp__floor__divide__c__kernel.html", null ],
    [ "dpnp_invert_c_kernel", "classdpnp__invert__c__kernel.html", null ],
    [ "dpnp_matmul_c_kernel", "classdpnp__matmul__c__kernel.html", null ],
    [ "dpnp_modf_c_kernel", "classdpnp__modf__c__kernel.html", null ],
    [ "dpnp_remainder_c_kernel", "classdpnp__remainder__c__kernel.html", null ],
    [ "DPNPFuncData", "struct_d_p_n_p_func_data.html", "struct_d_p_n_p_func_data" ]
];