var files_dup =
[
    [ "backend_fptr.hpp", "backend__fptr_8hpp_source.html", null ],
    [ "backend_iface.hpp", "backend__iface_8hpp_source.html", null ],
    [ "backend_iface_fft.hpp", "backend__iface__fft_8hpp_source.html", null ],
    [ "backend_iface_fptr.cpp", "backend__iface__fptr_8cpp_source.html", null ],
    [ "backend_iface_fptr.hpp", "backend__iface__fptr_8hpp_source.html", null ],
    [ "backend_pstl.hpp", "backend__pstl_8hpp_source.html", null ],
    [ "backend_utils.hpp", "backend__utils_8hpp_source.html", null ],
    [ "custom_1arg_1type_tbl.hpp", "custom__1arg__1type__tbl_8hpp_source.html", null ],
    [ "custom_1arg_2type_tbl.hpp", "custom__1arg__2type__tbl_8hpp_source.html", null ],
    [ "custom_2arg_1type_tbl.hpp", "custom__2arg__1type__tbl_8hpp_source.html", null ],
    [ "custom_2arg_3type_tbl.hpp", "custom__2arg__3type__tbl_8hpp_source.html", null ],
    [ "custom_kernels.cpp", "custom__kernels_8cpp_source.html", null ],
    [ "custom_kernels_bitwise.cpp", "custom__kernels__bitwise_8cpp_source.html", null ],
    [ "custom_kernels_elemwise.cpp", "custom__kernels__elemwise_8cpp_source.html", null ],
    [ "custom_kernels_linalg.cpp", "custom__kernels__linalg_8cpp_source.html", null ],
    [ "custom_kernels_manipulation.cpp", "custom__kernels__manipulation_8cpp_source.html", null ],
    [ "custom_kernels_mathematical.cpp", "custom__kernels__mathematical_8cpp_source.html", null ],
    [ "custom_kernels_random.cpp", "custom__kernels__random_8cpp_source.html", null ],
    [ "custom_kernels_reduction.cpp", "custom__kernels__reduction_8cpp_source.html", null ],
    [ "custom_kernels_searching.cpp", "custom__kernels__searching_8cpp_source.html", null ],
    [ "custom_kernels_sorting.cpp", "custom__kernels__sorting_8cpp_source.html", null ],
    [ "custom_kernels_statistics.cpp", "custom__kernels__statistics_8cpp_source.html", null ],
    [ "dpnp_kernels_fft.cpp", "dpnp__kernels__fft_8cpp_source.html", null ],
    [ "memory_sycl.cpp", "memory__sycl_8cpp_source.html", null ],
    [ "queue_sycl.cpp", "queue__sycl_8cpp_source.html", null ],
    [ "queue_sycl.hpp", "queue__sycl_8hpp_source.html", null ]
];