{% set version = "0.2" %}
{% set buildnumber = 0 %}

package:
    name: dpnp
    version: {{version}}

source:
    path: ..

requirements:
    host:
      - python
      - setuptools
      - numpy-devel >=1.18
      - cython
    run:
      - python

build:
    number: {{buildnumber}}
    include_recipe: False
    script_env:
      - ONEAPI_ROOT

test:
    requires:
      - pytest
    commands:
      - source ${ONEAPI_ROOT}/compiler/latest/env/vars.sh && python -c "import dpnp"

about:
    license: ISSL
    license_file: LICENSE.txt
    summary: NumPy-like API accelerated with SYCL
