{% set version = "0.0.1" %}
{% set buildnumber = 0 %}

package:
    name: dpnp
    version: {{version}}

source:
    path: ..

requirements:
    host:
      - python
      - setuptools
      - numpy-devel >=1.18
      - cython
    run:
      - python

build:
    number: {{buildnumber}}
    include_recipe: False
    script_env:
      - ONEAPI_ROOT

test:
    requires:
      - pytest
    commands:
      - ./conda-recipe/dpnp_run_ci.sh

about:
    license: ISSL
    license_file: LICENSE.txt
    summary: NumPy-like API accelerated with SYCL
