{% set version = "0.2" %}
{% set buildnumber = 0 %}

package:
    name: dpnp
    version: {{version}}

source:
    path: ..

requirements:
    host:
      - python
      - setuptools
      - numpy-devel >=1.18
      - cython
      - dpctl =0.3.3
    run:
      - python

build:
    number: {{buildnumber}}
    include_recipe: False
    script_env:
      - ONEAPI_ROOT

test:
    requires:
      - pytest
      - setuptools
      - dpctl =0.3.3
    source_files:
        - examples
        - tests
    commands:
      - python -c "import dpnp"
      - pytest

about:
    license: ISSL
    license_file: LICENSE.txt
    summary: NumPy-like API accelerated with SYCL
