{% set max_compiler_and_mkl_version = environ.get("MAX_BUILD_CMPL_MKL_VERSION", "2026.0a0") %}
{% set required_compiler_and_mkl_version = "2025.0" %}
{% set required_dpctl_version = "0.19.0*" %}

package:
    name: dpnp
    version: {{ GIT_DESCRIBE_TAG }}
source:
    path: ..

requirements:
    host:
      - python
      - pip >=24.0
      - setuptools >=69
      - numpy >=1.23
      - cython >=3.0.10
      - cmake >=3.29.0
      - ninja >=1.11.1 # [not win]
      - dpctl >={{ required_dpctl_version }}
      - intel-sycl-rt
      - intel-cmplr-lib-rt
      - mkl-devel-dpcpp >={{ required_compiler_and_mkl_version }},<{{ max_compiler_and_mkl_version }}
      - onedpl-devel
      - tbb-devel
      - wheel >=0.43
      - scikit-build >=0.17.0
      - level-zero-devel >=1.16
      - pybind11 >=2.12
      - python-build >=1.1
      - versioneer[toml] =0.29
      - tomli # [py<311]
    build:
      - {{ compiler('cxx') }}
      - {{ compiler('dpcpp') }} >={{ required_compiler_and_mkl_version }},<{{ max_compiler_and_mkl_version }}
      - sysroot_linux-64 >=2.28 # [linux]
    run:
      - python
      - {{ pin_compatible('dpctl', min_pin='x.x.x', max_pin=None) }}
      - {{ pin_compatible('dpcpp-cpp-rt', min_pin='x.x', max_pin='x') }}
      - {{ pin_compatible('onemkl-sycl-blas', min_pin='x.x', max_pin='x') }}
      - {{ pin_compatible('onemkl-sycl-dft', min_pin='x.x', max_pin='x') }}
      - {{ pin_compatible('onemkl-sycl-lapack', min_pin='x.x', max_pin='x') }}
      - {{ pin_compatible('onemkl-sycl-rng', min_pin='x.x', max_pin='x') }}
      - {{ pin_compatible('onemkl-sycl-stats', min_pin='x.x', max_pin='x') }}
      - {{ pin_compatible('onemkl-sycl-vm', min_pin='x.x', max_pin='x') }}
      - numpy
      - intel-gpu-ocl-icd-system

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    include_recipe: False
    script_env:
      - WHEELS_OUTPUT_FOLDER
      - OVERRIDE_INTEL_IPO  # [win]
    ignore_run_exports:
        - level-zero

test:
    requires:
      - pytest
      - setuptools

about:
    home: https://github.com/IntelPython/dpnp
    license: BSD-2-Clause
    license_file: LICENSE.txt
    summary: 'Data Parallel Extension for NumPy'
    description: |
        <strong>LEGAL NOTICE: Use of this software package is subject to the
        software license agreement (as set forth above, in the license section of
        the installed Conda package and/or the README file) and all notices,
        disclaimers or license terms for third party or open source software
        included in or with the software.</strong>
        <br/><br/>
        EULA: <a href="https://opensource.org/licenses/BSD-2-Clause" target="_blank">BSD-2-Clause</a>
        <br/><br/>

extra:
    recipe-maintainers:
        - oleksandr-pavlyk
        - antonwolfy
        - AlexanderKalistratov
        - vtavana
        - vlad-perevezentsev
