var searchData=
[
  ['gcdfunctor_0',['GcdFunctor',['../structdpnp_1_1kernels_1_1gcd_1_1_gcd_functor.html',1,'dpnp::kernels::gcd']]],
  ['gemmbatchtypepairsupportfactory_1',['GemmBatchTypePairSupportFactory',['../structdpnp_1_1extensions_1_1blas_1_1types_1_1_gemm_batch_type_pair_support_factory.html',1,'dpnp::extensions::blas::types']]],
  ['gemmtypepairsupportfactory_2',['GemmTypePairSupportFactory',['../structdpnp_1_1extensions_1_1blas_1_1types_1_1_gemm_type_pair_support_factory.html',1,'dpnp::extensions::blas::types']]],
  ['gemvtypepairsupportfactory_3',['GemvTypePairSupportFactory',['../structdpnp_1_1extensions_1_1blas_1_1types_1_1_gemv_type_pair_support_factory.html',1,'dpnp::extensions::blas::types']]],
  ['geqrfbatchtypepairsupportfactory_4',['GeqrfBatchTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_geqrf_batch_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['geqrftypepairsupportfactory_5',['GeqrfTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_geqrf_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['gesvdtypepairsupportfactory_6',['GesvdTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_gesvd_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['gesvtypepairsupportfactory_7',['GesvTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_gesv_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['get_5fdpnp_5ffunction_5fptr_8',['get_dpnp_function_ptr',['../group___b_a_c_k_e_n_d___a_p_i.html#ga257d96b384892c9c961137fa8f870a11',1,'dpnp_iface_fptr.hpp']]],
  ['get_5fdpnp_5ffunction_5fptr1_9',['get_dpnp_function_ptr1',['../group___b_a_c_k_e_n_d___a_p_i.html#gaeeb8d26a2589aecf1c30a64be90f6d92',1,'dpnp_iface_fptr.hpp']]],
  ['get_5fusm_5fdata_10',['get_usm_data',['../classdpctl_1_1tensor_1_1usm__ndarray.html#afacdda18871fc48d8c004d009ee71ada',1,'dpctl::tensor::usm_ndarray']]],
  ['getrfbatchtypepairsupportfactory_11',['GetrfBatchTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getrf_batch_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['getrftypepairsupportfactory_12',['GetrfTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getrf_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['getribatchtypepairsupportfactory_13',['GetriBatchTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getri_batch_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['getrsbatchtypepairsupportfactory_14',['GetrsBatchTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getrs_batch_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]],
  ['getrstypepairsupportfactory_15',['GetrsTypePairSupportFactory',['../structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getrs_type_pair_support_factory.html',1,'dpnp::extensions::lapack::types']]]
];
