var hierarchy =
[
    [ "statistics::sliding_window1d::_RegistryDataStorage< T, Size >", "classstatistics_1_1sliding__window1d_1_1___registry_data_storage.html", [
      [ "statistics::sliding_window1d::RegistryData< T, Size >", "structstatistics_1_1sliding__window1d_1_1_registry_data.html", [
        [ "statistics::sliding_window1d::RegistryWindow< T, Size >", "structstatistics_1_1sliding__window1d_1_1_registry_window.html", null ]
      ] ]
    ] ],
    [ "statistics::sliding_window1d::_RegistryDataStorage< T, 1 >", "classstatistics_1_1sliding__window1d_1_1___registry_data_storage.html", [
      [ "statistics::sliding_window1d::RegistryData< T, Size >", "structstatistics_1_1sliding__window1d_1_1_registry_data.html", null ]
    ] ],
    [ "ext::common::AtomicOp< T, Order, Scope >", "structext_1_1common_1_1_atomic_op.html", null ],
    [ "backend_sycl", "classbackend__sycl.html", null ],
    [ "dpnp::extensions::window::kernels::BartlettFactory< fnT, T >", "structdpnp_1_1extensions_1_1window_1_1kernels_1_1_bartlett_factory.html", null ],
    [ "dpnp::extensions::window::kernels::BartlettFunctor< T >", "classdpnp_1_1extensions_1_1window_1_1kernels_1_1_bartlett_functor.html", null ],
    [ "dpnp::kernels::erfs::BaseFunctor< OpT, ArgT, ResT >", "structdpnp_1_1kernels_1_1erfs_1_1_base_functor.html", null ],
    [ "dpnp::extensions::py_internal::elementwise_common::BinaryTwoOutputsContigFunctor< argT1, argT2, resT1, resT2, BinaryOperatorT, vec_sz, n_vecs, enable_sg_loadstore >", "structdpnp_1_1extensions_1_1py__internal_1_1elementwise__common_1_1_binary_two_outputs_contig_functor.html", null ],
    [ "dpnp::extensions::py_internal::elementwise_common::BinaryTwoOutputsStridedFunctor< argT1, argT2, resT1, resT2, FourOffsets_IndexerT, BinaryOperatorT >", "structdpnp_1_1extensions_1_1py__internal_1_1elementwise__common_1_1_binary_two_outputs_strided_functor.html", null ],
    [ "statistics::histogram::Bincount", "structstatistics_1_1histogram_1_1_bincount.html", null ],
    [ "dpnp::kernels::bitwise_count::BitwiseCountFunctor< argT, resT >", "structdpnp_1_1kernels_1_1bitwise__count_1_1_bitwise_count_functor.html", null ],
    [ "dpnp::extensions::window::kernels::BlackmanFactory< fnT, T >", "structdpnp_1_1extensions_1_1window_1_1kernels_1_1_blackman_factory.html", null ],
    [ "dpnp::extensions::window::kernels::BlackmanFunctor< T >", "classdpnp_1_1extensions_1_1window_1_1kernels_1_1_blackman_functor.html", null ],
    [ "std::bool_constant", null, [
      [ "dpnp::extensions::py_internal::type_dispatch::BinaryTypeMapTwoResultsEntry< Ty1, ArgTy1, Ty2, ArgTy2, ResTy1, ResTy2 >", "structdpnp_1_1extensions_1_1py__internal_1_1type__dispatch_1_1_binary_type_map_two_results_entry.html", null ],
      [ "dpnp::extensions::py_internal::type_dispatch::TypeMapTwoResultsEntry< Ty, ArgTy, ResTy1, ResTy2 >", "structdpnp_1_1extensions_1_1py__internal_1_1type__dispatch_1_1_type_map_two_results_entry.html", null ]
    ] ],
    [ "statistics::histogram::CachedData< T, Dims >", "structstatistics_1_1histogram_1_1_cached_data.html", null ],
    [ "dpnp::extensions::indexing::kernels::ChooseFunctor< ProjectorT, IndOutIndexerT, ChoicesIndexerT, IndT, T >", "classdpnp_1_1extensions_1_1indexing_1_1kernels_1_1_choose_functor.html", null ],
    [ "std::conjunction", null, [
      [ "are_same< T, Ts >", "structare__same.html", null ]
    ] ],
    [ "dpnp::kernels::degrees::DegreesFunctor< argT, resT >", "structdpnp_1_1kernels_1_1degrees_1_1_degrees_functor.html", null ],
    [ "dpnp::extensions::fft::DescriptorWrapper< prec, dom >", "classdpnp_1_1extensions_1_1fft_1_1_descriptor_wrapper.html", null ],
    [ "std::disjunction", null, [
      [ "is_any< T, Ts >", "structis__any.html", null ]
    ] ],
    [ "ext::common::DispatchTable< FnT >", "classext_1_1common_1_1_dispatch_table.html", null ],
    [ "ext::common::DispatchTable2< FnT >", "classext_1_1common_1_1_dispatch_table2.html", null ],
    [ "dpnp::kernels::divmod::DivmodFunctor< argT1, argT2, divT, modT >", "structdpnp_1_1kernels_1_1divmod_1_1_divmod_functor.html", null ],
    [ "dpnp::extensions::blas::DotcContigFactory< fnT, varT >", "structdpnp_1_1extensions_1_1blas_1_1_dotc_contig_factory.html", null ],
    [ "dpnp::extensions::blas::DotContigFactory< fnT, varT >", "structdpnp_1_1extensions_1_1blas_1_1_dot_contig_factory.html", null ],
    [ "dpnp::extensions::blas::types::DotcTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1blas_1_1types_1_1_dotc_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::blas::types::DotTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1blas_1_1types_1_1_dot_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::blas::DotuContigFactory< fnT, varT >", "structdpnp_1_1extensions_1_1blas_1_1_dotu_contig_factory.html", null ],
    [ "dpnp::extensions::blas::types::DotuTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1blas_1_1types_1_1_dotu_type_pair_support_factory.html", null ],
    [ "dpctl::detail::dpctl_capi", "classdpctl_1_1detail_1_1dpctl__capi.html", null ],
    [ "dpnp_less_comp", "classdpnp__less__comp.html", null ],
    [ "DPNPC_ptr_adapter< _DataType >", "class_d_p_n_p_c__ptr__adapter.html", null ],
    [ "DPNPFuncData", "struct_d_p_n_p_func_data.html", null ],
    [ "engine_struct", "structengine__struct.html", [
      [ "mcg59_struct", "structmcg59__struct.html", null ],
      [ "mt19937_struct", "structmt19937__struct.html", null ]
    ] ],
    [ "dpnp::kernels::erfs::ErfcinvOp", "structdpnp_1_1kernels_1_1erfs_1_1_erfcinv_op.html", null ],
    [ "dpnp::kernels::erfs::ErfcOp", "structdpnp_1_1kernels_1_1erfs_1_1_erfc_op.html", null ],
    [ "dpnp::kernels::erfs::ErfcxOp", "structdpnp_1_1kernels_1_1erfs_1_1_erfcx_op.html", null ],
    [ "dpnp::kernels::erfs::ErfinvOp", "structdpnp_1_1kernels_1_1erfs_1_1_erfinv_op.html", null ],
    [ "dpnp::kernels::erfs::ErfOp", "structdpnp_1_1kernels_1_1erfs_1_1_erf_op.html", null ],
    [ "std::exception", null, [
      [ "dpnp::extensions::lapack::LinAlgError", "classdpnp_1_1extensions_1_1lapack_1_1_lin_alg_error.html", null ]
    ] ],
    [ "dpnp::kernels::fabs::FabsFunctor< argT, resT >", "structdpnp_1_1kernels_1_1fabs_1_1_fabs_functor.html", null ],
    [ "dpnp::kernels::fix::FixFunctor< argT, resT >", "structdpnp_1_1kernels_1_1fix_1_1_fix_functor.html", null ],
    [ "dpnp::kernels::fmax::FmaxFunctor< argT1, argT2, resT >", "structdpnp_1_1kernels_1_1fmax_1_1_fmax_functor.html", null ],
    [ "dpnp::kernels::fmin::FminFunctor< argT1, argT2, resT >", "structdpnp_1_1kernels_1_1fmin_1_1_fmin_functor.html", null ],
    [ "dpnp::kernels::fmod::FmodFunctor< argT1, argT2, resT >", "structdpnp_1_1kernels_1_1fmod_1_1_fmod_functor.html", null ],
    [ "dpnp::kernels::frexp::FrexpFunctor< argT, mantT, expT >", "structdpnp_1_1kernels_1_1frexp_1_1_frexp_functor.html", null ],
    [ "dpnp::kernels::gcd::GcdFunctor< argT1, argT2, resT >", "structdpnp_1_1kernels_1_1gcd_1_1_gcd_functor.html", null ],
    [ "dpnp::extensions::blas::types::GemmBatchTypePairSupportFactory< Tab, Tc >", "structdpnp_1_1extensions_1_1blas_1_1types_1_1_gemm_batch_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::blas::types::GemmTypePairSupportFactory< Tab, Tc >", "structdpnp_1_1extensions_1_1blas_1_1types_1_1_gemm_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::blas::types::GemvTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1blas_1_1types_1_1_gemv_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::lapack::types::GeqrfBatchTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1lapack_1_1types_1_1_geqrf_batch_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::lapack::types::GeqrfTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1lapack_1_1types_1_1_geqrf_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::lapack::types::GesvdTypePairSupportFactory< T, RealT >", "structdpnp_1_1extensions_1_1lapack_1_1types_1_1_gesvd_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::lapack::types::GesvTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1lapack_1_1types_1_1_gesv_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::lapack::types::GetrfBatchTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getrf_batch_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::lapack::types::GetrfTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getrf_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::lapack::types::GetriBatchTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getri_batch_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::lapack::types::GetrsBatchTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getrs_batch_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::lapack::types::GetrsTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1lapack_1_1types_1_1_getrs_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::window::kernels::HammingFactory< fnT, T >", "structdpnp_1_1extensions_1_1window_1_1kernels_1_1_hamming_factory.html", null ],
    [ "dpnp::extensions::window::kernels::HammingFunctor< T >", "classdpnp_1_1extensions_1_1window_1_1kernels_1_1_hamming_functor.html", null ],
    [ "dpnp::extensions::window::kernels::HanningFactory< fnT, T >", "structdpnp_1_1extensions_1_1window_1_1kernels_1_1_hanning_factory.html", null ],
    [ "dpnp::extensions::window::kernels::HanningFunctor< T >", "classdpnp_1_1extensions_1_1window_1_1kernels_1_1_hanning_functor.html", null ],
    [ "dpnp::kernels::heaviside::HeavisideFunctor< argT1, argT2, resT >", "structdpnp_1_1kernels_1_1heaviside_1_1_heaviside_functor.html", null ],
    [ "dpnp::extensions::lapack::types::HeevdTypePairSupportFactory< T, RealT >", "structdpnp_1_1extensions_1_1lapack_1_1types_1_1_heevd_type_pair_support_factory.html", null ],
    [ "statistics::histogram::HistGlobalMemory< T >", "structstatistics_1_1histogram_1_1_hist_global_memory.html", null ],
    [ "statistics::histogram::HistLocalType< T >", "structstatistics_1_1histogram_1_1_hist_local_type.html", null ],
    [ "statistics::histogram::HistLocalType< int64_t >", "structstatistics_1_1histogram_1_1_hist_local_type_3_01int64__t_01_4.html", null ],
    [ "statistics::histogram::HistLocalType< uint64_t >", "structstatistics_1_1histogram_1_1_hist_local_type_3_01uint64__t_01_4.html", null ],
    [ "statistics::histogram::Histogram", "structstatistics_1_1histogram_1_1_histogram.html", null ],
    [ "statistics::histogram::histogram_kernel< T, HistImpl, Edges, Weights >", "classstatistics_1_1histogram_1_1histogram__kernel.html", null ],
    [ "statistics::histogram::Histogramdd", "structstatistics_1_1histogram_1_1_histogramdd.html", null ],
    [ "statistics::histogram::HistWithLocalCopies< T, localT >", "structstatistics_1_1histogram_1_1_hist_with_local_copies.html", null ],
    [ "dpnp::kernels::i0::I0Functor< argT, resT >", "structdpnp_1_1kernels_1_1i0_1_1_i0_functor.html", null ],
    [ "ext::common::TableBuilder2< FnT, SupportedTypes, Func >::impl< _FnT, T1, T2 >", "structext_1_1common_1_1_table_builder2_1_1impl.html", null ],
    [ "ext::common::TableBuilder< FnT, SupportedTypes, Func >::impl< _FnT, T >", "structext_1_1common_1_1_table_builder_1_1impl.html", null ],
    [ "ext::common::int_pair_hash", "structext_1_1common_1_1int__pair__hash.html", null ],
    [ "dpnp::kernels::isclose::IsCloseContigScalarFunctor< T, scT, resTy, vec_sz, n_vecs, enable_sg_loadstore >", "structdpnp_1_1kernels_1_1isclose_1_1_is_close_contig_scalar_functor.html", null ],
    [ "dpnp::kernels::isclose::IsCloseStridedScalarFunctor< T, scT, resTy, ThreeOffsets_IndexerT >", "structdpnp_1_1kernels_1_1isclose_1_1_is_close_strided_scalar_functor.html", null ],
    [ "ext::common::IsNan< T >", "structext_1_1common_1_1_is_nan.html", null ],
    [ "dpnp::kernels::lcm::LcmFunctor< argT1, argT2, resT >", "structdpnp_1_1kernels_1_1lcm_1_1_lcm_functor.html", null ],
    [ "dpnp::kernels::ldexp::LdexpFunctor< argT1, argT2, resT >", "structdpnp_1_1kernels_1_1ldexp_1_1_ldexp_functor.html", null ],
    [ "ext::common::Less< T >", "structext_1_1common_1_1_less.html", null ],
    [ "dpnp::kernels::logaddexp2::Logaddexp2Functor< argT1, argT2, resT >", "structdpnp_1_1kernels_1_1logaddexp2_1_1_logaddexp2_functor.html", null ],
    [ "dpctl::utils::detail::ManagedMemory", "structdpctl_1_1utils_1_1detail_1_1_managed_memory.html", null ],
    [ "dpnp::kernels::modf::ModfFunctor< argT, fractT, intT >", "structdpnp_1_1kernels_1_1modf_1_1_modf_functor.html", null ],
    [ "dpnp::kernels::nan_to_num::NanToNumContigFunctor< T, scT, vec_sz, n_vecs, enable_sg_loadstore >", "structdpnp_1_1kernels_1_1nan__to__num_1_1_nan_to_num_contig_functor.html", null ],
    [ "dpnp::kernels::nan_to_num::NanToNumFunctor< T, scT, InOutIndexerT >", "structdpnp_1_1kernels_1_1nan__to__num_1_1_nan_to_num_functor.html", null ],
    [ "statistics::histogram::NoWeights< T >", "structstatistics_1_1histogram_1_1_no_weights.html", null ],
    [ "dpnp::extensions::indexing::strides_detail::NthStrideOffsetUnpacked", "structdpnp_1_1extensions_1_1indexing_1_1strides__detail_1_1_nth_stride_offset_unpacked.html", null ],
    [ "pybind11::object", null, [
      [ "dpctl::memory::usm_memory", "classdpctl_1_1memory_1_1usm__memory.html", null ],
      [ "dpctl::tensor::usm_ndarray", "classdpctl_1_1tensor_1_1usm__ndarray.html", null ]
    ] ],
    [ "ext::common::one_of< T, Rest >", "structext_1_1common_1_1one__of.html", null ],
    [ "ext::common::one_of< T, std::tuple< Top > >", "structext_1_1common_1_1one__of_3_01_t_00_01std_1_1tuple_3_01_top_01_4_01_4.html", null ],
    [ "ext::common::one_of< T, std::tuple< Top, Rest... > >", "structext_1_1common_1_1one__of_3_01_t_00_01std_1_1tuple_3_01_top_00_01_rest_8_8_8_01_4_01_4.html", null ],
    [ "dpnp::extensions::lapack::types::OrgqrBatchTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1lapack_1_1types_1_1_orgqr_batch_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::lapack::types::OrgqrTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1lapack_1_1types_1_1_orgqr_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::lapack::types::PotrfBatchTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1lapack_1_1types_1_1_potrf_batch_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::lapack::types::PotrfTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1lapack_1_1types_1_1_potrf_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::fft::PrecisionType< prec >", "structdpnp_1_1extensions_1_1fft_1_1_precision_type.html", null ],
    [ "dpnp::extensions::fft::PrecisionType< mkl_dft::precision::DOUBLE >", "structdpnp_1_1extensions_1_1fft_1_1_precision_type_3_01mkl__dft_1_1precision_1_1_d_o_u_b_l_e_01_4.html", null ],
    [ "dpnp::extensions::fft::PrecisionType< mkl_dft::precision::SINGLE >", "structdpnp_1_1extensions_1_1fft_1_1_precision_type_3_01mkl__dft_1_1precision_1_1_s_i_n_g_l_e_01_4.html", null ],
    [ "dpnp::kernels::radians::RadiansFunctor< argT, resT >", "structdpnp_1_1kernels_1_1radians_1_1_radians_functor.html", null ],
    [ "dpnp::extensions::fft::ScaleType< prec, dom, is_forward >", "structdpnp_1_1extensions_1_1fft_1_1_scale_type.html", null ],
    [ "dpnp::extensions::fft::ScaleType< prec, mkl_dft::domain::COMPLEX, is_fwd >", "structdpnp_1_1extensions_1_1fft_1_1_scale_type_3_01prec_00_01mkl__dft_1_1domain_1_1_c_o_m_p_l_e_x_00_01is__fwd_01_4.html", null ],
    [ "dpnp::extensions::fft::ScaleType< prec, mkl_dft::domain::REAL, false >", "structdpnp_1_1extensions_1_1fft_1_1_scale_type_3_01prec_00_01mkl__dft_1_1domain_1_1_r_e_a_l_00_01false_01_4.html", null ],
    [ "dpnp::extensions::fft::ScaleType< prec, mkl_dft::domain::REAL, true >", "structdpnp_1_1extensions_1_1fft_1_1_scale_type_3_01prec_00_01mkl__dft_1_1domain_1_1_r_e_a_l_00_01true_01_4.html", null ],
    [ "dpnp::kernels::sinc::SincFunctor< argT, Tp >", "structdpnp_1_1kernels_1_1sinc_1_1_sinc_functor.html", null ],
    [ "statistics::sliding_window1d::sliding_window1d_kernel< WorkPI, T, SizeT, Op, Red >", "classstatistics_1_1sliding__window1d_1_1sliding__window1d__kernel.html", null ],
    [ "statistics::sliding_window1d::sliding_window1d_small_kernel< WorkPI, T, SizeT, Op, Red >", "classstatistics_1_1sliding__window1d_1_1sliding__window1d__small__kernel.html", null ],
    [ "statistics::sliding_window1d::SlidingDotProduct1d", "structstatistics_1_1sliding__window1d_1_1_sliding_dot_product1d.html", null ],
    [ "dpnp::kernels::spacing::SpacingFunctor< argT, resT >", "structdpnp_1_1kernels_1_1spacing_1_1_spacing_functor.html", null ],
    [ "statistics::sliding_window1d::Span< T, SizeT >", "classstatistics_1_1sliding__window1d_1_1_span.html", null ],
    [ "statistics::sliding_window1d::Span< T, size_t >", "classstatistics_1_1sliding__window1d_1_1_span.html", [
      [ "statistics::sliding_window1d::PaddedSpan< T, SizeT >", "classstatistics_1_1sliding__window1d_1_1_padded_span.html", null ]
    ] ],
    [ "dpnp::extensions::lapack::types::SyevdTypePairSupportFactory< T, RealT >", "structdpnp_1_1extensions_1_1lapack_1_1types_1_1_syevd_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::blas::types::SyrkTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1blas_1_1types_1_1_syrk_type_pair_support_factory.html", null ],
    [ "ext::common::TableBuilder< FnT, SupportedTypes, Func >", "structext_1_1common_1_1_table_builder.html", null ],
    [ "ext::common::TableBuilder2< FnT, SupportedTypes, Func >", "structext_1_1common_1_1_table_builder2.html", null ],
    [ "std::true_type", null, [
      [ "dpnp::extensions::py_internal::type_dispatch::DefaultTwoResultsEntry< Ty >", "structdpnp_1_1extensions_1_1py__internal_1_1type__dispatch_1_1_default_two_results_entry.html", null ]
    ] ],
    [ "pybind11::detail::type_caster< sycl::context >", "structpybind11_1_1detail_1_1type__caster_3_01sycl_1_1context_01_4.html", null ],
    [ "pybind11::detail::type_caster< sycl::device >", "structpybind11_1_1detail_1_1type__caster_3_01sycl_1_1device_01_4.html", null ],
    [ "pybind11::detail::type_caster< sycl::event >", "structpybind11_1_1detail_1_1type__caster_3_01sycl_1_1event_01_4.html", null ],
    [ "pybind11::detail::type_caster< sycl::half >", "structpybind11_1_1detail_1_1type__caster_3_01sycl_1_1half_01_4.html", null ],
    [ "pybind11::detail::type_caster< sycl::kernel >", "structpybind11_1_1detail_1_1type__caster_3_01sycl_1_1kernel_01_4.html", null ],
    [ "pybind11::detail::type_caster< sycl::kernel_bundle< sycl::bundle_state::executable > >", "structpybind11_1_1detail_1_1type__caster_3_01sycl_1_1kernel__bundle_3_01sycl_1_1bundle__state_1_1executable_01_4_01_4.html", null ],
    [ "pybind11::detail::type_caster< sycl::queue >", "structpybind11_1_1detail_1_1type__caster_3_01sycl_1_1queue_01_4.html", null ],
    [ "dpnp::extensions::py_internal::elementwise_common::UnaryTwoOutputsContigFunctor< argT, resT1, resT2, UnaryTwoOutputsOpT, vec_sz, n_vecs, enable_sg_loadstore >", "structdpnp_1_1extensions_1_1py__internal_1_1elementwise__common_1_1_unary_two_outputs_contig_functor.html", null ],
    [ "dpnp::extensions::py_internal::elementwise_common::UnaryTwoOutputsStridedFunctor< argT, resT1, resT2, IndexerT, UnaryTwoOutputsOpT >", "structdpnp_1_1extensions_1_1py__internal_1_1elementwise__common_1_1_unary_two_outputs_strided_functor.html", null ],
    [ "statistics::histogram::UncachedData< T, Dims >", "structstatistics_1_1histogram_1_1_uncached_data.html", null ],
    [ "dpnp::extensions::lapack::types::UngqrBatchTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1lapack_1_1types_1_1_ungqr_batch_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::lapack::types::UngqrTypePairSupportFactory< T >", "structdpnp_1_1extensions_1_1lapack_1_1types_1_1_ungqr_type_pair_support_factory.html", null ],
    [ "dpnp::extensions::lapack::helper::value_type_of< T >", "structdpnp_1_1extensions_1_1lapack_1_1helper_1_1value__type__of.html", null ],
    [ "dpnp::extensions::lapack::helper::value_type_of< std::complex< T > >", "structdpnp_1_1extensions_1_1lapack_1_1helper_1_1value__type__of_3_01std_1_1complex_3_01_t_01_4_01_4.html", null ],
    [ "ext::common::value_type_of_impl< T, hasValueType >", "structext_1_1common_1_1value__type__of__impl.html", null ],
    [ "ext::common::value_type_of_impl< T, false >", "structext_1_1common_1_1value__type__of__impl_3_01_t_00_01false_01_4.html", null ],
    [ "ext::common::value_type_of_impl< T, true >", "structext_1_1common_1_1value__type__of__impl_3_01_t_00_01true_01_4.html", null ],
    [ "statistics::histogram::Weights< T >", "structstatistics_1_1histogram_1_1_weights.html", null ]
];